{% set name = "napari-cryofibsem-monitor" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-cryofibsem-monitor-{{ version }}.tar.gz
  sha256: 549692b7602df4ab69513041a1ca17d5f58930576bb64269139f662ce0ff0d58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - imreg_dft
    - matplotlib-base
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >={{ python_min }}
    - tifffile

test:
  imports:
    - napari_cryofibsem_monitor
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jojoelfe/napari-cryofibsem-monitor
  summary: A plugin to monitor the creation of lamella using AutoTEM on a TFS Acquilos instrument
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jojoelfe
